name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch: true

jobs:
  build:
    runs-on: python:3-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON files
        run: |
          python -mjson.tool 'de.json' > /dev/null
          python -mjson.tool 'module.json' > /dev/null
